apiVersion: v1
kind: Template

metadata:
  name: admin-ui

parameters:
  - name: APPLICATION_NAME
    value: admin-ui
    required: true
  - name: ROUTE_NAME
    value: admin
    required: true
  - name: REPLICAS
    value: "1"
    required: true
  - name: IMAGE_REPOSITORY
    displayName: Image Repository
    value: quay.io/redhatdemo/2020-admin-ui:latest
    required: true
  - name: CONTAINER_REQUEST_CPU
    value: 200m
  - name: CONTAINER_REQUEST_MEMORY
    value: 300Mi
  - name: CONTAINER_LIMIT_CPU
    value: 200m
  - name: CONTAINER_LIMIT_MEMORY
    value: 300Mi
  - name: KEY
  - name: CERTIFICATE
  - name: CA_CERTIFICATE

objects:
  - apiVersion: v1
    kind: DeploymentConfig
    metadata:
      labels:
        app: ${APPLICATION_NAME}
      name: ${APPLICATION_NAME}
    spec:
      replicas: ${{REPLICAS}}
      revisionHistoryLimit: 2
      selector:
        app: ${APPLICATION_NAME}
      strategy:
        rollingParams:
          timeoutSeconds: 3600
        type: Rolling
      template:
        metadata:
          labels:
            app: ${APPLICATION_NAME}
        spec:
          containers:
            - image: ${IMAGE_REPOSITORY}
              imagePullPolicy: Always
              name: ${APPLICATION_NAME}
              ports:
                - containerPort: 8080
                  name: http
                  protocol: TCP
              resources:
                requests:
                  cpu: ${CONTAINER_REQUEST_CPU}
                  memory: ${CONTAINER_REQUEST_MEMORY}
                limits:
                  cpu: ${CONTAINER_LIMIT_CPU}
                  memory: ${CONTAINER_LIMIT_MEMORY}
      triggers:
        - type: ConfigChange


  - apiVersion: v1
    kind: Service
    metadata:
      labels:
        app: ${APPLICATION_NAME}
      name: ${APPLICATION_NAME}
    spec:
      ports:
        - name: http
          port: 8080
      selector:
        app: ${APPLICATION_NAME}

  - apiVersion: v1
    kind: Route
    metadata:
      labels:
        app: ${APPLICATION_NAME}
      name: ${ROUTE_NAME}
    spec:
      port:
        targetPort: 8080
      to:
        kind: Service
        name: ${APPLICATION_NAME}

#  - kind: Ingress
#    apiVersion: extensions/v1beta1
#    metadata:
#      labels:
#        app: ${APPLICATION_NAME}
#      name: ${ROUTE_NAME}
#    spec:
#      rules:
#        - host: game.apps-crc.testing
#          http:
#            paths:
#              - path: /api
#                backend:
#                  serviceName: admin-server
#                  servicePort: 8080+
#              - path: /
#                backend:
#                  serviceName: admin-ui
#                  servicePort: 8080