apiVersion: v1
kind: Template

labels:
  application: demo-common

metadata:
  name: demo-common

parameters:
  - name: SECRET_NAME
    value: demo-common
    required: true
  - name: S3_ACCESS_KEY_ID
    value: ""
  - name: S3_SECRET_ACCESS_KEY
    value: ""
  - name: S3_ENDPOINT
    value: ""
  - name: S3_REGION
    value: ""
  - name: S3_BUCKET
    value: ""
  - name: S3_PREFIX
    value: ""


objects:
  - apiVersion: v1
    kind: Secret
    metadata:
      name: ${SECRET_NAME}
    data:
    stringData:
      S3_ACCESS_KEY_ID: "${S3_ACCESS_KEY_ID}"
      S3_SECRET_ACCESS_KEY: "${S3_SECRET_ACCESS_KEY}"
      S3_ENDPOINT: "${S3_ENDPOINT}"
      S3_REGION: "${S3_REGION}"
      S3_BUCKET: "${S3_BUCKET}"
      S3_PREFIX: "${S3_PREFIX}"
