apiVersion: v1
kind: Template

labels:
  application: demo-common

metadata:
  name: demo-common

parameters:
  - name: SECRET_NAME
    value: 2020-demo-common
    required: true


objects:
  - apiVersion: v1
    kind: Secret
    metadata:
      name: ${SECRET_NAME}
    data:
    stringData:
      SHARED_SECRET: "SHARED"
